name=ESP32Syslog
version=1.0.2
author=jnovonj
maintainer=jnovonj
sentence=Syslog library for ESP32 with automatic ESP_LOG redirection.
paragraph=Intercepts system logs and sends them via UDP with an offline circular buffer.
category=Communication
url=https://github.com/jnovonj/ESP32Syslog
architectures=esp32
includes=ESP32Syslog.h